### ISSUE TITLE
bug: Display the list info in the user selected language instead of German

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Kuirl#78]
**Describe the bug**
When I create a new list, with a label and description, first in my default language (my user language, english for example) and then in German and French. The label and description displayed in the accordion menu are in **German** and not in English.

**To Reproduce**

1. Go to 'http://localhost:4200/project/0001/lists'
1. Create a new list, fill in the fields in different languages (keep in mind the default language of the form)
1. See error

**Expected behavior**
The default language should be displayed instead of the German version all the time.

**Screenshots**
<img width="1045" alt="Screen Shot 2019-09-13 at 10 22 44" src="https://user-images.githubusercontent.com/29532462/64849664-27fb9580-d614-11e9-84f8-2959010da854.png">

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
I suggest to build a pipe that handles the value output of stringLiteral array in user's default language. I already opened a new branch in Knora-ui to shorten / truncate strings. I will generate this pipe in the same branch ([action-truncate-pipe](https://github.com/dhlab-basel/Knora-ui/tree/wip/action-truncate-pipe)), because the truncate pipe will be used together with the stringLiteral value output e.g. in a long description:

![Screenshot 2019-09-13 at 11 08 57](https://user-images.githubusercontent.com/4253580/64851032-e5878800-d616-11e9-9339-98eede7475b1.png)
