### ISSUE TITLE
bug: Login failed in Safari

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Kuirl#88]
**Describe the bug**
The login failed when I try to log in with either a user member or a system admin account in **Safari**.

**To Reproduce**

1. Go to your local kuirl app
1. Click on login
1. Login with right credentials
1. See error

**Expected behavior**
Login and redirect to the dashboard or the ongoing search url. 

**Screenshots**
<img width="1280" alt="Screenshot 2019-09-25 at 14 16 18" src="https://user-images.githubusercontent.com/29532462/65599953-5461cb00-df9f-11e9-8903-c3ffe14a6742.png">

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.6
- Browser: Safari
- Version: 12.1.2

**Additional context**
I have tried the same process with 3 different branches: master, documentation-link and fix-issue-85.

**Comment by kilchenmann** [comment]
That's bad. I was able to reproduce and I'm wondering. First it's a caching problem, second it seems to be a problem with the localstorage. It doesn't store the session information correct. There's no username stored. I can try to solve it this evening.

**Comment by kilchenmann** [comment]
It's really strange. The bug is in @knora/authentication and the main problem is the authentication in the API. It doesn't store the Knora API cookie but I receive the JWT. The workflow is as follow:
- Login -> post to authentication route and get JWT
- User -> get information about logged-in user
    - In Chrome: no problem
    - In Safari: get the same information as a user who is not logged in
- Session -> set session with information about logged-in user. But in Safari I don't get the whole user information.

Right now I don't now how to solve it. I'm using Safari v13.0.0

**Comment by subotic** [comment]
> Right now I don't know how to solve it. I'm using Safari v13.0.0

Maybe there is a problem with Safari v13.0.0? Safari v13.0.1 is out. Maybe this will work?

**Comment by kilchenmann** [comment]
> Maybe there is a problem with Safari v13.0.0? Safari v13.0.1 is out. Maybe this will work?

This is not the issue because Flavie is using Safari 12.1.2 (see first comment).

Safari doesn't store the Knora-API cookie. We get the following information with the authentication post (login):

![Screenshot 2019-09-26 at 10 18 19](https://user-images.githubusercontent.com/4253580/65671134-fbe60880-e046-11e9-94ed-1dbbcafc0d61.png)

But there's no Cookie on the Knora-API URL, in our case: `http://0.0.0.0:3333/`

It works fine in Chrome and Firefox.

**Comment by kilchenmann** [comment]
I tested the login with the same @knora/authentication version which is running on the test-server (9.0.0.) but I get the same problems in safari. I will test another solution but not now...

**Comment by kilchenmann** [comment]
The jwt interceptor from @knora/authentication was not well implemented anymore resp. there was no export of it. In this case the front-end doesn't need the set-cookie from Knora api anymore (but sipi does?). The request should work now with jwt. It's solved in dhlab-basel/knora-ui#332

**Comment by subotic** [comment]
> but sipi does?

Cookies are needed for the IIIF viewers (openseadragon, etc.) to work, i.e., be able to have access to images needing authentication.

**Comment by kilchenmann** [comment]
Thank you @subotic for clarification. 

> Cookies are needed for the IIIF viewers (openseadragon, etc.) to work, i.e., be able to have access to images needing authentication.

This is something we have to keep in mind. Let's see if the set-cookie issue is local only.
